export const apiRoutes = {
  auth: {
    signIn: '/auth/sign-in',
    signUp: '/auth/sign-up',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    session: '/auth/session',
  },
  home: '/home',
  categories: '/categories',
  categoryDetail: (slug: string) => `/categories/${slug}`,
  creators: '/creators',
  creatorDetail: (id: string) => `/creators/${id}`,
  lives: '/lives',
  liveDetail: (id: string) => `/lives/${id}`,
  livePublish: (id: string) => `/lives/${id}/publish`,
  liveRoom: (id: string) => `/lives/${id}/room`,
  premiumContent: '/premium-content',
  premiumContentDetail: (id: string) => `/premium-content/${id}`,
  classes: '/classes',
  classDetail: (id: string) => `/classes/${id}`,
  notifications: '/notifications',
  search: '/search',
  checkout: '/checkout',
  profileSettings: '/users/settings',
  transactions: '/transactions',
  viewerDashboard: '/viewer/dashboard',
  creatorDashboard: '/creator/dashboard',
  creatorPayouts: '/creator/payouts',
  adminDashboard: '/admin/dashboard',
} as const;
