export const apiRoutes = {
  auth: {
    signIn: '/auth/sign-in',
    signUp: '/auth/sign-up',
    signInWithGoogle: '/auth/google',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    emailVerificationRequest: '/auth/verify-email/resend',
    emailVerificationConfirm: '/auth/verify-email',
    completeProfile: '/auth/complete-profile',
    linkGoogleAccount: '/auth/link/google',
    linkPassword: '/auth/link/password',
    session: '/auth/session',
  },
  home: '/home',
  categories: '/categories',
  categoryDetail: (slug: string) => `/categories/${slug}`,
  creators: '/creators',
  creatorDetail: (id: string) => `/creators/${id}`,
  lives: '/lives',
  liveDetail: (id: string) => `/lives/${id}`,
  livePublish: (id: string) => `/lives/${id}/publish`,
  liveRoom: (id: string) => `/lives/${id}/room`,
  premiumContent: '/premium-content',
  premiumContentDetail: (id: string) => `/premium-content/${id}`,
  classes: '/classes',
  classDetail: (id: string) => `/classes/${id}`,
  notifications: '/notifications',
  notificationRead: (id: string) => `/notifications/${id}/read`,
  search: '/search',
  checkout: '/checkout',
  profileSettings: '/users/settings',
  transactions: '/transactions',
  viewerDashboard: '/viewer/dashboard',
  creatorDashboard: '/creator/dashboard',
  creatorPayouts: '/creator/payouts',
  adminDashboard: '/admin/dashboard',
  accessConfirmPurchase: '/v1/access/transactions/confirm',
  accessGrantStatus: (targetType: 'live_session' | 'premium_content' | 'class' | 'lesson' | 'private_live_invite', targetId: string) =>
    `/v1/access/grants/${targetType}/${targetId}`,
  liveJoinCheck: (id: string) => `/v1/lives/${id}/join-check`,
  liveChatHistory: (id: string, limit = 40) => `/v1/lives/${id}/chat?limit=${limit}`,
  liveAttendance: (id: string) => `/v1/lives/${id}/attendance`,
} as const;
